### ISSUE TITLE
[RESOLVED] Can not save/load file 

### ISSUE THREAD

**Issue by Trantienloc2411** [HaiLeVN/J1.L.P0021.-PetStoreManagment-500-Map#1]
![image](https://user-images.githubusercontent.com/62489239/216611720-9b1ea6c7-31ae-4549-b41f-1c3b682357a0.png)
I can not store or load data from your files. Can you check it ?

**Comment by HaiLeVN** [comment]
Maybe your file path to folder output does not exist. If it exists, please check my new code update and test it again.

![image](https://user-images.githubusercontent.com/37034176/216644761-4361dd04-9246-469c-92ba-fdd1ee289ec0.png)
